# Generated by Django 5.2.4 on 2025-08-07 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomparticipant',
            options={'ordering': ['-last_seen']},
        ),
        migrations.AlterModelOptions(
            name='userpresence',
            options={'ordering': ['-last_seen']},
        ),
    ]
