# Generated by Django 5.2.4 on 2025-08-07 14:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_sprint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['-joined_at']},
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['team', 'status'], name='projects_team_id_8db465_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='projects_status_6303d7_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['start_date', 'end_date'], name='projects_start_d_cb24a6_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['created_by'], name='projects_created_428cb1_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['created_at'], name='projects_created_40bcd1_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['name'], name='projects_name_3fb8fb_idx'),
        ),
        migrations.AddIndex(
            model_name='sprint',
            index=models.Index(fields=['project', 'status'], name='sprints_project_d1ab01_idx'),
        ),
        migrations.AddIndex(
            model_name='sprint',
            index=models.Index(fields=['start_date', 'end_date'], name='sprints_start_d_264577_idx'),
        ),
        migrations.AddIndex(
            model_name='sprint',
            index=models.Index(fields=['status'], name='sprints_status_94255a_idx'),
        ),
        migrations.AddIndex(
            model_name='sprint',
            index=models.Index(fields=['created_at'], name='sprints_created_a3a0ba_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['created_by'], name='teams_created_35f209_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['created_at'], name='teams_created_d88c0c_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['name'], name='teams_name_12b53a_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['team', 'user'], name='team_member_team_id_61cdbf_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['user'], name='team_member_user_id_906d63_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['role'], name='team_member_role_76b2ff_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['joined_at'], name='team_member_joined__413a4d_idx'),
        ),
    ]
