# Generated by Django 5.2.4 on 2025-07-30 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
        ('projects', '0003_sprint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(max_length=100)),
                ('team_name', models.CharField(max_length=200)),
                ('access_token', models.TextField()),
                ('bot_user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('bot_access_token', models.TextField(blank=True, null=True)),
                ('webhook_url', models.URLField(blank=True, null=True)),
                ('scope', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slack_integration', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'slack_integrations',
                'unique_together': {('user', 'team_id')},
            },
        ),
        migrations.CreateModel(
            name='SlackChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=100)),
                ('channel_name', models.CharField(max_length=200)),
                ('is_private', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('notification_types', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slack_channels', to='projects.project')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='integrations.slackintegration')),
            ],
            options={
                'db_table': 'slack_channels',
                'unique_together': {('integration', 'channel_id')},
            },
        ),
        migrations.CreateModel(
            name='SlackMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('notification', 'Notification'), ('command_response', 'Command Response'), ('webhook', 'Webhook')], default='notification', max_length=20)),
                ('slack_timestamp', models.CharField(blank=True, max_length=20, null=True)),
                ('text', models.TextField()),
                ('attachments', models.JSONField(default=list)),
                ('blocks', models.JSONField(default=list)),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('sent_successfully', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='integrations.slackchannel')),
            ],
            options={
                'db_table': 'slack_messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
