# Generated by Django 5.2.4 on 2025-07-31 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_discordintegration_discordchannel_discordmessage_and_more'),
        ('projects', '0003_sprint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCalendarIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('calendar_id', models.CharField(default='primary', max_length=500)),
                ('google_user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('scope', models.TextField(default='https://www.googleapis.com/auth/calendar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_calendar_integration', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'google_calendar_integrations',
            },
        ),
        migrations.CreateModel(
            name='CalendarSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(default='full', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('events_synced', models.IntegerField(default=0)),
                ('events_created', models.IntegerField(default=0)),
                ('events_updated', models.IntegerField(default=0)),
                ('events_deleted', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sync_token', models.CharField(blank=True, max_length=500, null=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_records', to='integrations.googlecalendarintegration')),
            ],
            options={
                'db_table': 'calendar_sync_records',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_event_id', models.CharField(max_length=1024, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('timezone', models.CharField(default='UTC', max_length=100)),
                ('all_day', models.BooleanField(default=False)),
                ('recurring', models.BooleanField(default=False)),
                ('recurrence_rule', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('tentative', 'Tentative'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20)),
                ('transparency', models.CharField(choices=[('opaque', 'Busy'), ('transparent', 'Free')], default='opaque', max_length=20)),
                ('attendees', models.JSONField(default=list)),
                ('creator_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('organizer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('hangout_link', models.URLField(blank=True, null=True)),
                ('meeting_url', models.URLField(blank=True, null=True)),
                ('visibility', models.CharField(default='default', max_length=20)),
                ('reminders', models.JSONField(default=list)),
                ('google_created_at', models.DateTimeField()),
                ('google_updated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='projects.project')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='integrations.googlecalendarintegration')),
            ],
            options={
                'db_table': 'calendar_events',
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='MeetingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('meeting_type', models.CharField(choices=[('standup', 'Daily Standup'), ('planning', 'Sprint Planning'), ('review', 'Sprint Review'), ('retrospective', 'Sprint Retrospective'), ('general', 'General Meeting'), ('one_on_one', 'One-on-One')], default='general', max_length=20)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('timezone', models.CharField(default='UTC', max_length=100)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('meeting_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('recurring', models.BooleanField(default=False)),
                ('recurrence_pattern', models.JSONField(default=dict)),
                ('agenda', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('action_items', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendees', models.ManyToManyField(blank=True, related_name='scheduled_meetings', to=settings.AUTH_USER_MODEL)),
                ('calendar_event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_schedule', to='integrations.calendarevent')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_meetings', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='projects.project')),
            ],
            options={
                'db_table': 'meeting_schedules',
                'ordering': ['start_datetime'],
            },
        ),
    ]
