# Generated by Django 5.2.4 on 2025-08-07 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_googlecalendarintegration_calendarsync_calendarevent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discordchannel',
            options={'ordering': ['position', 'channel_name']},
        ),
        migrations.AlterModelOptions(
            name='discordcommand',
            options={'ordering': ['command_name']},
        ),
        migrations.AlterModelOptions(
            name='discordintegration',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='discordrole',
            options={'ordering': ['-position', 'role_name']},
        ),
        migrations.AlterModelOptions(
            name='githubintegration',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='githubissue',
            options={'ordering': ['-github_updated_at']},
        ),
        migrations.AlterModelOptions(
            name='githubrepository',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='githubwebhook',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='googlecalendarintegration',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='slackchannel',
            options={'ordering': ['channel_name']},
        ),
        migrations.AlterModelOptions(
            name='slackintegration',
            options={'ordering': ['-created_at']},
        ),
    ]
