# Generated by Django 5.2.4 on 2025-08-07 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectmetrics',
            options={'ordering': ['-last_calculated']},
        ),
        migrations.AlterModelOptions(
            name='taskmetrics',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='teammembermetrics',
            options={'ordering': ['-period_start']},
        ),
    ]
